### PR TITLE
fix: Fixing Implementation of GoogleAuth.sign() for external account credentials

### LINKED ISSUE #1239: Mismatched signature when signing with impersonated credentials
A user of the cloud storage node library has reported an [issue](https://github.com/googleapis/nodejs-storage/issues/1550) when trying to sign URLs using Workload Identity Federation. The sign url feature of the library ultimately uses GoogleAuth.sign(), so in this case I think it should be resolving to the [recently implemented](https://github.com/googleapis/google-auth-library-nodejs/pull/1227/files) case for signing with impersonated credentials. Evidently, it *does* sign, it just produces a different signature than when the credentials and private key are used directly. Possibly some issue where the wrong email ends up getting used?

### PR DESCRIPTION
**Pull request by aeitzman**
Currently, creating signed storage URLs does not work for external account credentials because the storage library expects client_email to be returned from GoogleAuth.getCredentials(). Changing the logic so the same client email that is used to the sign the blob (extracted from the Service Account Impersonation URL) is returned from the getCredentials() call.

Fixes #1239  🦕

### CODE REVIEW

**Comment by aeitzman** [comment]
@lsirac

File: src/auth/googleauth.ts [hunk 1]
```diff
@@ -752,7 +754,14 @@ export class GoogleAuth<T extends AuthClient = JSONClient> {
...
 
   private async getCredentialsAsync(): Promise<CredentialBody> {
-    await this.getClient();
+    const client = await this.getClient();
+
+    if (
+      client instanceof BaseExternalAccountClient &&
+      client.getServiceAccountEmail()
+    ) {
+      return {client_email: client.getServiceAccountEmail() as string};
```
Comment (bcoe) [inline src/auth/googleauth.ts:763]: what if you check whether or not this is null in the `if`, then you don't need `as string`.

**Review by bcoe — APPROVED** [review]

File: test/test.googleauth.ts [hunk 2]
```diff
@@ -2340,6 +2340,18 @@ describe('googleauth', () => {
         assert.deepStrictEqual(res.data, data);
         scopes.forEach(s => s.done());
       });
+
+      it('getCredentials() should return the service account email for external accounts', async () => {
```
Comment (bcoe) [inline test/test.googleauth.ts:2344]: Nit, You could do:

```
describe('getCredentials()', () => {
  it('should return the service account email for external accounts', async () => 
  {
        // Set up a mock to return path to a valid credentials file.
        const email = saEmail;
        const configWithImpersonation = createExternalAccountJSON();
        configWithImpersonation.service_account_impersonation_url =
          getServiceAccountImpersonationUrl();
        const auth = new GoogleAuth({credentials: configWithImpersonation});
        const body = await auth.getCredentials();
        assert.notStrictEqual(null, body);
        assert.strictEqual(email, body.client_email);
      });
});
```

So that tests read a bit better.

File: src/auth/googleauth.ts [hunk 3]
```diff
@@ -730,8 +730,10 @@ export class GoogleAuth<T extends AuthClient = JSONClient> {
   /**
    * The callback function handles a credential object that contains the
    * client_email and private_key (if exists).
-   * getCredentials checks for these values from the user JSON at first.
-   * If it doesn't exist, and the environment is on GCE, it gets the
+   * getCredentials first checks if the client is using an external account and
+   * uses the service account email in place of client_email
```
Comment (lsirac) [inline src/auth/googleauth.ts:734]: missing period

File: src/auth/googleauth.ts [hunk 4]
```diff
@@ -730,8 +730,10 @@ export class GoogleAuth<T extends AuthClient = JSONClient> {
...
+   * if that doesn't exist, it checks for these values from the user JSON.
```
Comment (lsirac) [inline src/auth/googleauth.ts:735]: If

**Review by lsirac — APPROVED** [review]
