### PR TITLE
test: Flaky Test Fixes

### LINKED ISSUE #1577: googleauth googleauth: getCredentials should error if metadata server is not reachable failed
Note: #1266 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 070ec96b78dc26791bacb452ebef13d0a5ae6b18
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/80c97f3f-c93b-47d1-b12e-25f9c4388c93), [Sponge](http://sponge2/80c97f3f-c93b-47d1-b12e-25f9c4388c93)
status: failed
<details><summary>Test output</summary><br><pre>The input did not match the regular expression /Unsuccessful response status code. Request failed with status code 404/. Input:

'FetchError: request to http://169.254.169.254/computeMetadata/v1/instance/service-accounts/?recursive=true failed, reason: Nock: No match for request {\n' +
  '  "method": "GET",\n' +
  '  "url": "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/?recursive=true",\n' +
  '  "headers": {\n' +
  '    "metadata-flavor": [\n' +
  '      "Google"\n' +
  '    ],\n' +
  '    "accept": [\n' +
  '      "*/*"\n' +
  '    ],\n' +
  '    "user-agent": [\n' +
  '      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"\n' +
  '    ],\n' +
  '    "accept-encoding": [\n' +
  '      "gzip,deflate"\n' +
  '    ],\n' +
  '    "connection": [\n' +
  '      "close"\n' +
  '    ]\n' +
  '  }\n' +
  '}'

AssertionError [ERR_ASSERTION]: The input did not match the regular expression /Unsuccessful response status code. Request failed with status code 404/. Input:

'FetchError: request to http://169.254.169.254/computeMetadata/v1/instance/service-accounts/?recursive=true failed, reason: Nock: No match for request {\n' +
  '  "method": "GET",\n' +
  '  "url": "http://169.254.169.254/computeMetadata/v1/instance/service-accounts/?recursive=true",\n' +
  '  "headers": {\n' +
  '    "metadata-flavor": [\n' +
  '      "Google"\n' +
  '    ],\n' +
  '    "accept": [\n' +
  '      "*/*"\n' +
  '    ],\n' +
  '    "user-agent": [\n' +
  '      "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"\n' +
  '    ],\n' +
  '    "accept-encoding": [\n' +
  '      "gzip,deflate"\n' +
  '    ],\n' +
  '    "connection": [\n' +
  '      "close"\n' +
  '    ]\n' +
  '  }\n' +
  '}'

    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Context.<anonymous> (build/test/test.googleauth.js:991:13)
        -> /workspace/test/test.googleauth.ts:1234:7</pre></details>

### PR DESCRIPTION
**Pull request by danielbankhead**
Fixes #1577

🦕

### CODE REVIEW

File: test/test.googleauth.ts [hunk 1]
```diff
@@ -1173,36 +1170,6 @@ describe('googleauth', () => {
...
-        nock(HOST_ADDRESS).get(svcAccountPath).reply(200, {}),
-      ];
-      await auth._checkIsGCE();
-      assert.strictEqual(true, auth.isGCE);
-      await assert.rejects(
-        auth.getCredentials(),
-        /Invalid response from metadata service: incorrect Metadata-Flavor header./
-      );
-      scopes.forEach(s => s.done());
-    });
```
Comment (danielbankhead) [inline test/test.googleauth.ts:1204]: These tests are already in `gcp-metadata` here:

https://github.com/googleapis/gcp-metadata/blob/4f65c04bc3b9469ebaf71bd36f4403dcaa8b50c5/test/index.test.ts#L153-L180

**Review by aeitzman — APPROVED** [review]
