### PR TITLE
fix: move accessToken to headers instead of parameter

### LINKED ISSUE #980: Send access_token for token info method as a header instead of as URL params
Found this one, not sure if there are others:

https://github.com/googleapis/google-auth-library-nodejs/blob/42e60c46ce4a463f4c50bf4226d945c38146398b/src/auth/oauth2client.ts#L1016-L1020

/cc @JustinBeckwith

### PR DESCRIPTION
**Pull request by sofisl**
Fixes #980

### CODE REVIEW

File: src/auth/oauth2client.ts [hunk 1]
```diff
@@ -1018,9 +1018,9 @@ export class OAuth2Client extends AuthClient {
       method: 'POST',
       headers: {
         'Content-Type': 'application/x-www-form-urlencoded',
+        'Authorization': `Bearer ${accessToken}`,
```
Comment (bcoe) [inline src/auth/oauth2client.ts:1021]:
```suggestion
        Authorization: `Bearer ${accessToken}`,
```

File: src/auth/oauth2client.ts [hunk 2]
```diff
@@ -1018,9 +1018,9 @@ export class OAuth2Client extends AuthClient {
...
       },
-      url: OAuth2Client.GOOGLE_TOKEN_INFO_URL,
-      data: querystring.stringify({access_token: accessToken}),
+      url: OAuth2Client.GOOGLE_TOKEN_INFO_URL
```
Comment (bcoe) [inline src/auth/oauth2client.ts:1023]:
```suggestion
      url: OAuth2Client.GOOGLE_TOKEN_INFO_URL,
```

**Review by bcoe — APPROVED** [review]
LGTM 👍
